# docker compose file for the project React + Node + MongoDB Atlas

services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - WEATHER_API_KEY=62eb0c54fb21437a87c185842231007

  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
